; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#define RootDirectory "Balanza\Balanza\bin\Debug\"
#define MyAppName "BALANZA"  
#define MyAppIcon "BALANZA.ico"  
#define MyAppUninstallIcon "BALANZA.ico"  
#define MyAppAccesoDirectoName ="BALANZA" 
;#define MyAppAccesoDirectoName = MyAppName
#define MyAppPublisher "Gerardo Godino"
#define MyAppURL "https://logical.net.ar"
#define MyAppInfoURL "https://logical.net.ar"
#define MyAppUpdateInfoURL "https://logical.net.ar/"
#define MyAppExeName "Balanza.exe" 
                                                          
#define VerMajor
#define VerMinor
#define VerRev
#define VerBuild
#define FullVersion=ParseVersion(RootDirectory + MyAppExeName, VerMajor, VerMinor, VerRev, VerBuild)
;#define MyAppVersion = Str(VerMajor) + "." + Str(VerMinor) + "." + Str(VerBuild)
#define MyAppVersion GetFileVersion(RootDirectory + MyAppExeName)



[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{8B88E0BD-023D-4334-85FC-9FBCFD8C817B} 
AppName={#MyAppName}
AppVersion={#MyAppVersion} 
AppVerName={#MyAppName} version {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=C:\{#MyAppName} 
DisableDirPage=yes
DisableReadyPage=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
OutputDir=INSTALADORES
OutputBaseFilename=BALANZA_Installer_v{#MyAppVersion}   
;;;;;;;;SetupIconFile=ICONOS\{#MyAppIcon}
Compression=lzma
SolidCompression=yes
CreateUninstallRegKey=no   
UninstallFilesDir={code:NewTargetDir}                             
UninstallDisplayName={#MyAppName} {code:GetUninstallName}
UninstallDisplayIcon={code:NewTargetDir}\{#MyAppUninstallIcon}
UsePreviousLanguage=no  
VersionInfoVersion={#MyAppVersion}
VersionInfoCompany=Logical Systems
VersionInfoDescription=Aplicacion para la captura de pesos e impresion de tickt
VersionInfoTextVersion={#MyAppVersion}
VersionInfoCopyright=2024
VersionInfoProductName={#MyAppName}
VersionInfoProductVersion={#MyAppVersion}
VersionInfoProductTextVersion={#MyAppVersion}

[Languages]
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Files]
;Ejecutable
Source: "Balanza\Balanza\bin\Debug\Balanza.exe"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion
;Icono de aplicacion


;Configuracion de conexion
;Source: "INSTALADORES\configuracion\conexion-produccion.ora"; DestDir: "{code:NewTargetDir}"; DestName: "conexion.ora"; Components: produccion
;Source: "INSTALADORES\configuracion\conexion-testeo.ora"; DestDir: "{code:NewTargetDir}"; DestName: "conexion.ora"; Components: testeo
;Source: "INSTALADORES\configuracion\conexion-desarrollo.ora"; DestDir: "{code:NewTargetDir}"; DestName: "conexion.ora"; Components: desarrollo
;Source: "INSTALADORES\configuracion\conexion_hist-produccion.ora"; DestDir: "{code:NewTargetDir}"; DestName: "conexion_hist.ora"; Components: produccion
;Source: "INSTALADORES\configuracion\conexion_hist-testeo.ora"; DestDir: "{code:NewTargetDir}"; DestName: "conexion_hist.ora"; Components: testeo
;Source: "INSTALADORES\configuracion\conexion_hist-desarrollo.ora"; DestDir: "{code:NewTargetDir}"; DestName: "conexion_hist.ora"; Components: desarrollo

;Configuracion de conexion
Source: "Datos\DB_BASSO.accdb"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion

;Archivo de Parametria
Source: "Balanza\Balanza\bin\Debug\Balanza.exe.Config"; DestDir: "{code:NewTargetDir}"; Flags:  ignoreversion

;Imagenes
;Source: "Imagenes\Iconos\*.*"; DestDir: "{code:NewTargetDir}\Imagenes\Iconos"
;Librerias
Source: "\Balanza\Balanza\bin\Debug\EnvDTE.dll"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion
Source: "\Balanza\Balanza\bin\Debug\EnvDTE.xml"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion
Source: "\Balanza\Balanza\bin\Debug\Microsoft.MSXML.dll"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion
Source: "\Balanza\Balanza\bin\Debug\stdole.dll"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion
Source: "\Balanza\Balanza\bin\Debug\System.Configuration.ConfigurationManager.dll"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion
Source: "\Balanza\Balanza\bin\Debug\System.Configuration.ConfigurationManager.xml"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion
Source: "\Balanza\Balanza\bin\Debug\System.Data.OleDb.dll"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion
Source: "\Balanza\Balanza\bin\Debug\System.Data.OleDb.xml"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion

;Librerias para Reporte
Source: "\Balanza\Balanza\bin\Debug\Microsoft.ReportViewer.Common.dll"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion
Source: "\Balanza\Balanza\bin\Debug\Microsoft.ReportViewer.DataVisualization.dll"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion
Source: "\Balanza\Balanza\bin\Debug\Microsoft.ReportViewer.Design.dll"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion
Source: "\Balanza\Balanza\bin\Debug\Microsoft.ReportViewer.ProcessingObjectModel.dll"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion
Source: "\Balanza\Balanza\bin\Debug\Microsoft.ReportViewer.WinForms.dll"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion
Source: "\Balanza\Balanza\bin\Debug\Microsoft.SqlServer.Types.dll"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion


;ReportesPlantillas
Source: "\Balanza\Balanza\bin\Debug\Report.rdlc"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion

;[Tasks]
;Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Icons]
Name: "{group}\{#MyAppName}{code:GetComponent}"; Filename: "{code:NewTargetDir}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppAccesoDirectoName}{code:GetComponent}"; Filename: "{code:NewTargetDir}\{#MyAppExeName}"

;Name: "{commondesktop}\{#MyAppName}{code:GetComponent}"; Filename: "{code:NewTargetDir}\{#MyAppExeName}"
;Name: "{group}\{#MyAppAccess}"; Filename: "{app}\{#MyAppExeName}"
;Name: "{commondesktop}\{#MyAppAccess}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{code:NewTargetDir}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
;Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Components]
Name: "produccion"; Description: "{#MyAppName} (Produccion)"; Types: produccion; Flags: exclusive
Name: "testeo"; Description: "{#MyAppName} (Testeo)"; Types: testeo; Flags: exclusive
Name: "desarrollo"; Description: "{#MyAppName} (Desarrollo)"; Types: desarrollo; Flags: exclusive

[Types]
Name: "produccion"; Description: "{#MyAppName} (Produccion)"
Name: "testeo"; Description: "{#MyAppName} (Testeo)"
Name: "desarrollo"; Description: "{#MyAppName} (Desarrollo)"

[Dirs]
Name: "{code:NewTargetDir}\Tickets"


[Code]
function GetDirSize(Path: String): Int64;
var
  FindRec: TFindRec;
  FilePath: string;
  Size: Int64;
begin
  if FindFirst(Path + '\*', FindRec) then
  begin
    Result := 0;
    try
      repeat
        if (FindRec.Name <> '.') and (FindRec.Name <> '..') then
        begin
          FilePath := Path + '\' + FindRec.Name;
          if (FindRec.Attributes and FILE_ATTRIBUTE_DIRECTORY) <> 0 then
          begin
            Size := GetDirSize(FilePath);
          end
            else
          begin
            Size := Int64(FindRec.SizeHigh) shl 32 + FindRec.SizeLow;
          end;
          Result := Result + Size;
        end;
      until not FindNext(FindRec);
    finally
      FindClose(FindRec);
    end;
  end
    else
  begin
    Log(Format('Failed to list %s', [Path]));
    Result := -1;
  end;
end;
 
function GetDate(dummy: String): String;
begin
  Result := GetDateTimeString('yyyymmdd',#0,#0);
end;

function GetType(Value: String): string;
begin
  if IsComponentSelected('desarrollo') then
    begin Result := 'desarrollo'; end
  else if IsComponentSelected('testeo') then
    begin Result := 'testeo'; end
  else
    begin Result := 'produccion'; end;
end;


function GetComponent(Value: String): string;
begin
  if IsComponentSelected('desarrollo') then
    begin Result := '_DESA'; end
  else if IsComponentSelected('testeo') then
    begin Result := '_TEST'; end
  else
    begin Result := ''; end;
end; 

function NewTargetDir(Value: String): String;
begin
  Result := ExpandConstant('{app}') + GetComponent('') ;
end;

function GetUninstallName(Value: String): string;
begin
  if IsComponentSelected('desarrollo') then
    begin Result := ' (Desarrollo)'; end
  else if IsComponentSelected('testeo') then
    begin Result := ' (Testeo)'; end
  else
    begin Result := ''; end;
end;

function GetInstallSize(dummy: String): String;
begin
  Result := IntToStr(GetDirSize(NewTargetDir(''))/1024);
end;





