; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#define RootDirectory "Balanza\Balanza\bin\Debug\"
#define MyAppName "Balanza"  
#define MyAppIcon "Balanza.ico"  
#define MyAppUninstallIcon "Balanza.ico"  
#define MyAppAccesoDirectoName ="Balanza" 
;#define MyAppAccesoDirectoName = MyAppName
#define MyAppPublisher "Gerardo Godino"
#define MyAppURL "https://logical.net.ar"
#define MyAppInfoURL "https://logical.net.ar"
#define MyAppUpdateInfoURL "https://logical.net.ar/"
#define MyAppExeName "Balanza.exe" 
                                                          
#define VerMajor
#define VerMinor
#define VerRev
#define VerBuild
#define FullVersion=ParseVersion(RootDirectory + MyAppExeName, VerMajor, VerMinor, VerRev, VerBuild)
;#define MyAppVersion = Str(VerMajor) + "." + Str(VerMinor) + "." + Str(VerBuild)
#define MyAppVersion GetFileVersion(RootDirectory + MyAppExeName)
;#define MyAppAccess "SIMON C#"


[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{8B88E0BD-023D-4334-85FC-9FBCFD8C817B} 
AppName={#MyAppName}
AppVersion={#MyAppVersion} 
AppVerName={#MyAppName} version {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=C:\{#MyAppName} ;DefaultDirName=C:\SIMON{code:GetComponent}\{#MyAppName}
DisableDirPage=yes
DisableReadyPage=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
OutputDir=INSTALADORES
OutputBaseFilename=Balanza_Installer_v{#MyAppVersion}   
;;;;;;;;SetupIconFile=ICONOS\{#MyAppIcon}
Compression=lzma
SolidCompression=yes
CreateUninstallRegKey=no   
UninstallFilesDir={code:NewTargetDir}                             
UninstallDisplayName={#MyAppName} {code:GetUninstallName}
UninstallDisplayIcon={code:NewTargetDir}\{#MyAppUninstallIcon}
UsePreviousLanguage=no  
VersionInfoVersion={#MyAppVersion}
VersionInfoCompany=Logical Systems
VersionInfoDescription=Aplicacion BALANZ administrativa de Correo Argentino S.A.
VersionInfoTextVersion={#MyAppVersion}
VersionInfoCopyright=2024
VersionInfoProductName={#MyAppName}
VersionInfoProductVersion={#MyAppVersion}
VersionInfoProductTextVersion={#MyAppVersion}

[Languages]
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Files]
;Ejecutable
Source: "Balanza\Balanza\bin\Debug\Balanza.exe"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion
;Icono de aplicacion
;Source: "ICONOS\Simon.ico"; DestDir: "{code:NewTargetDir}"
;Base de Datos 
Source: "Datos\DB_BASSO.accdb"; DestDir: "{code:NewTargetDir}"; DestName: "DB_BASSO.accdb"; Components: produccion

;Archivo de Parametria
Source: "Balanza\Balanza\bin\Debug\Balanza.exe.Config"; DestDir: "{code:NewTargetDir}"; Flags:  ignoreversion

;Imagenes
;Source: "Imagenes\logoCorreo2020.jpg"; DestDir: "{code:NewTargetDir}\Imagenes"
;Source: "Imagenes\LogoReportes.jpg"; DestDir: "{code:NewTargetDir}\Imagenes"
;Source: "Imagenes\Iconos\*.*"; DestDir: "{code:NewTargetDir}\Imagenes\Iconos"








;Librerias
Source: "SIMON\SIMON\bin\Debug\Oracle.DataAccess.dll"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion

Source: "SIMON\SIMON\bin\Debug\itextsharp.dll"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\BouncyCastle.Crypto.dll"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion
;Source: "SIMON\SIMON\bin\Debug\System.Net.Http.dll"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion
;Source: "ABM Giros\ABM_Giros\bin\Release\Oracle.DataAccess.dll"; DestDir: "{app}"; Flags: ignoreversion

;Librerias para Reporte
Source: "SIMON\SIMON\bin\Debug\Microsoft.ReportViewer.Common.dll"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\Microsoft.ReportViewer.DataVisualization.dll"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\Microsoft.ReportViewer.Design.dll"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\Microsoft.ReportViewer.ProcessingObjectModel.dll"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\Microsoft.ReportViewer.WinForms.dll"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\Microsoft.SqlServer.Types.dll"; DestDir: "{code:NewTargetDir}"; Flags: ignoreversion


;ReportesPlantillas
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptAlertaPagosDistintasSucursales.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptAnaliticoPagos.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptBenefBloqueadosXNivel.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptBeneficiosBloqueados.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptBusquedaBeneficios.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptCambioBoca.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptCambioCanal.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptCambioEstadoComprobantes.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptCambioFechas.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptCierreMensual.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptCierreMensualNIS.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptComisionOpeRendidos.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptConfirmacionNovedades.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptConsultaSucursales.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptControlFisico.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptEncajeDinamicoNroDocumento.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptEncajeDinamicoResumido.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptEncajeEstaticoNroDocumento.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptEncajeEstaticoResumido.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptEncaminamiento.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptEstadoCuentas.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptFallecidos.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptHistoricidad910_910.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptHistoricidad910_NIS.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptHistoricoBeneficios.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptInformeGralBeneficioExpandido.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptInformeGralBeneficioNormal.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptInformeGralBeneficioTotales.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptListadoComprobantePagoControl.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptListadoComprobantePagoExpandido.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptListadoComprobantePagoNormal.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptOperativosDepurados.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptPagoBloqueoFallecidos.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptReciboProvisorio.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptReporteTesoreria.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptRetencionLiberacion.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptSintesisXOperativoCierreConDetalle.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptSintesisXOperativoCierreConDetalleZona.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptSintesisXOperativoCierreSinDetalle.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptSintesisXOperativoCierreSinDetalleZona.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptSintesisXOperativoTransfConDetalle.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptSintesisXOperativoTransfConDetalleZona.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptSintesisXOperativoTransfSinDetalle.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptSintesisXOperativoTransfSinDetalleZona.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptTotalesXProvincia.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion
Source: "SIMON\SIMON\bin\Debug\ReportesPlantillas\Plantillas\RptTotalesXProvinciaSinOPE.rdlc"; DestDir: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"; Flags: ignoreversion


;[Tasks]
;Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Icons]
Name: "{group}\{#MyAppName}{code:GetComponent}"; Filename: "{code:NewTargetDir}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppAccesoDirectoName}{code:GetComponent}"; Filename: "{code:NewTargetDir}\{#MyAppExeName}"

;Name: "{commondesktop}\{#MyAppName}{code:GetComponent}"; Filename: "{code:NewTargetDir}\{#MyAppExeName}"
;Name: "{group}\{#MyAppAccess}"; Filename: "{app}\{#MyAppExeName}"
;Name: "{commondesktop}\{#MyAppAccess}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{code:NewTargetDir}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
;Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Components]
Name: "produccion"; Description: "{#MyAppName} (Produccion)"; Types: produccion; Flags: exclusive
Name: "testeo"; Description: "{#MyAppName} (Testeo)"; Types: testeo; Flags: exclusive
Name: "desarrollo"; Description: "{#MyAppName} (Desarrollo)"; Types: desarrollo; Flags: exclusive

[Types]
Name: "produccion"; Description: "{#MyAppName} (Produccion)"
Name: "testeo"; Description: "{#MyAppName} (Testeo)"
Name: "desarrollo"; Description: "{#MyAppName} (Desarrollo)"

[Dirs]
Name: "{code:NewTargetDir}\Imagenes"
Name: "{code:NewTargetDir}\ReportesPlantillas"
Name: "{code:NewTargetDir}\ReportesPlantillas\Plantillas"

[InstallDelete]
Type: dirifempty; Name: "{app}"
[Registry]
Root: "HKLM32"; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}{code:GetUninstallName}"; Flags: uninsdeletekey 

Root: "HKLM32"; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}{code:GetUninstallName}"; ValueType: string; ValueName: "Inno Setup: Setup Version"; ValueData: "6.0.3 (u)";
Root: "HKLM32"; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}{code:GetUninstallName}"; ValueType: string; ValueName: "Inno Setup: App Path"; ValueData: "{code:NewTargetDir}";
Root: "HKLM32"; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}{code:GetUninstallName}"; ValueType: string; ValueName: "InstallLocation"; ValueData: "{code:NewTargetDir}";
Root: "HKLM32"; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}{code:GetUninstallName}"; ValueType: string; ValueName: "Inno Setup: Icon Group"; ValueData: "{#MyAppName}";
Root: "HKLM32"; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}{code:GetUninstallName}"; ValueType: string; ValueName: "Inno Setup: User"; ValueData: "{username}";
Root: "HKLM32"; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}{code:GetUninstallName}"; ValueType: string; ValueName: "Inno Setup: Setup Type"; ValueData: "{code:GetType}";
Root: "HKLM32"; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}{code:GetUninstallName}"; ValueType: string; ValueName: "Inno Setup: Selected Components"; ValueData: "{code:GetType}";

Root: "HKLM32"; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}{code:GetUninstallName}"; ValueType: string; ValueName: "DisplayName"; ValueData: "{#MyAppName}{code:GetUninstallName}";
Root: "HKLM32"; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}{code:GetUninstallName}"; ValueType: string; ValueName: "DisplayIcon"; ValueData: "{code:NewTargetDir}\{#MyAppIcon}";
Root: "HKLM32"; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}{code:GetUninstallName}"; ValueType: string; ValueName: "UninstallString"; ValueData: "{code:NewTargetDir}\unins000.exe";
Root: "HKLM32"; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}{code:GetUninstallName}"; ValueType: string; ValueName: "QuietUninstallString"; ValueData: "{code:NewTargetDir}\unins000.exe /SILENT";
Root: "HKLM32"; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}{code:GetUninstallName}"; ValueType: string; ValueName: "DisplayVersion"; ValueData: "{#MyAppVersion}";
Root: "HKLM32"; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}{code:GetUninstallName}"; ValueType: string; ValueName: "Publisher"; ValueData: "{#MyAppPublisher}";
Root: "HKLM32"; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}{code:GetUninstallName}"; ValueType: string; ValueName: "URLInfoAbout"; ValueData: "{#MyAppURL}";
Root: "HKLM32"; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}{code:GetUninstallName}"; ValueType: string; ValueName: "HelpLink"; ValueData: "{#MyAppInfoURL}";
Root: "HKLM32"; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}{code:GetUninstallName}"; ValueType: string; ValueName: "URLUpdateInfo"; ValueData: "{#MyAppUpdateInfoURL}";
Root: "HKLM32"; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}{code:GetUninstallName}"; ValueType: dword ; ValueName: "NoModify"; ValueData: 0x00000001;
Root: "HKLM32"; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}{code:GetUninstallName}"; ValueType: dword ; ValueName: "NoRepair"; ValueData: 0x00000001;
Root: "HKLM32"; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}{code:GetUninstallName}"; ValueType: string ; ValueName: "InstallDate"; ValueData: "{code:GetDate}";
Root: "HKLM32"; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}{code:GetUninstallName}"; ValueType: dword ; ValueName: "MajorVersion"; ValueData: {#VerMajor};
Root: "HKLM32"; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}{code:GetUninstallName}"; ValueType: dword ; ValueName: "MinorVersion"; ValueData: {#VerMinor};
Root: "HKLM32"; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}{code:GetUninstallName}"; ValueType: dword ; ValueName: "VersionMajor"; ValueData: {#VerMajor};
Root: "HKLM32"; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}{code:GetUninstallName}"; ValueType: dword ; ValueName: "VersionMinor"; ValueData: {#VerMinor};
Root: "HKLM32"; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}{code:GetUninstallName}"; ValueType: dword ; ValueName: "EstimatedSize"; ValueData: {code:GetInstallSize};

[Code]
function GetDirSize(Path: String): Int64;
var
  FindRec: TFindRec;
  FilePath: string;
  Size: Int64;
begin
  if FindFirst(Path + '\*', FindRec) then
  begin
    Result := 0;
    try
      repeat
        if (FindRec.Name <> '.') and (FindRec.Name <> '..') then
        begin
          FilePath := Path + '\' + FindRec.Name;
          if (FindRec.Attributes and FILE_ATTRIBUTE_DIRECTORY) <> 0 then
          begin
            Size := GetDirSize(FilePath);
          end
            else
          begin
            Size := Int64(FindRec.SizeHigh) shl 32 + FindRec.SizeLow;
          end;
          Result := Result + Size;
        end;
      until not FindNext(FindRec);
    finally
      FindClose(FindRec);
    end;
  end
    else
  begin
    Log(Format('Failed to list %s', [Path]));
    Result := -1;
  end;
end;
 
function GetDate(dummy: String): String;
begin
  Result := GetDateTimeString('yyyymmdd',#0,#0);
end;

function GetType(Value: String): string;
begin
  if IsComponentSelected('desarrollo') then
    begin Result := 'desarrollo'; end
  else if IsComponentSelected('testeo') then
    begin Result := 'testeo'; end
  else
    begin Result := 'produccion'; end;
end;


function GetComponent(Value: String): string;
begin
  if IsComponentSelected('desarrollo') then
    begin Result := '_DESA'; end
  else if IsComponentSelected('testeo') then
    begin Result := '_TEST'; end
  else
    begin Result := ''; end;
end; 

function NewTargetDir(Value: String): String;
begin
  Result := ExpandConstant('{app}') + GetComponent('') + '\SIMON_C#';
end;

function GetUninstallName(Value: String): string;
begin
  if IsComponentSelected('desarrollo') then
    begin Result := ' (Desarrollo)'; end
  else if IsComponentSelected('testeo') then
    begin Result := ' (Testeo)'; end
  else
    begin Result := ''; end;
end;

function GetInstallSize(dummy: String): String;
begin
  Result := IntToStr(GetDirSize(NewTargetDir(''))/1024);
end;





